name: Backend CI/CD
on:
    push:
        paths:
            - 'backend/**'
            - '.github/workflows/backend-ci.yml'
    pull_request:
        paths:
            - 'backend/**'
    repository_dispatch:
        types: [trigger-backend]
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3


            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'


            - name: Install dependencies
              run: |
                cd backend
                pip install -r requirements.txt
                pip install -r requirements-dev.txt


            - name: Run tests
              run: |
                cd backend
                python -m pytest -v


            - name: Install jq
              run: sudo apt-get install jq


            - name: Create Deployment package
              run: |
                cd backend
                mkdir deploy_package
                cp app.py deploy_package/
                cp requirements.txt deploy_package/
                cd deploy_package
                pip install -r requirements.txt -t .
                zip -r ../lambda_function.zip .


            - name: Deploy to Lambda
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: 'us-east-1'
              run: |


                # Check AWS CLI version
                aws --version || (
                  curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                  unzip awscliv2.zip
                  sudo ./aws/install
                )

                # Fetch Terraform outputs
                TERRAFORM_OUTPUT=$(aws s3 cp s3://terraform-output-bucket-yashk/terraform-output.json -)
                LAMBDA_FUNCTION_NAME=$(echo $TERRAFORM_OUTPUT | jq -r '.lambda_function_name.value')

                cd backend
                aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --zip-file fileb://lambda_function.zip

                