name: Frontend CI/CD
on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
  pull_request:
    paths:
      - 'frontend/**'
  repository_dispatch:
    types: [trigger-frontend]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      # - name: Run Tests
      #   run: |
      #     cd frontend
      #     npm test

      - name: Build Project
        run: |
          cd frontend
          npm run build
      
      - name: Install jq
        run: sudo apt-get install jq
        

      - name: Deploy to S3 and Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |

          # Check AWS CLI version
          aws --version || (
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          )
          
          # Fetch Terraform outputs
          TERRAFORM_OUTPUT=$(aws s3 cp s3://terraform-output-bucket-yashk/terraform-output.json -)
          S3_BUCKET_NAME=$(echo $TERRAFORM_OUTPUT | jq -r '.s3_bucket_name.value')
          CLOUDFRONT_DIST_ID=$(echo $TERRAFORM_OUTPUT | jq -r '.cloudfront_distribution_id.value')

          # Deploy to S3
          aws s3 sync out/ s3://$S3_BUCKET_NAME --delete

          # Invalidate CloudFront cache
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID --paths '/*'
